name: SimpleGems
version: '${project.version}'
main: me.refracdevelopment.simplegems.SimpleGems
authors:
  - RefracDevelopment
api-version: '1.13'
depend:
  - NBTAPI
softdepend:
  - PlaceholderAPI
  - Skulls
  - HeadDatabase
  - ItemsAdder
description: SimpleGems is a plugin that adds a custom gems economy into minecraft.
website: https://discord.gg/EFeSKPg739
folia-supported: true