name: SimpleGems
version: '${project.version}'
main: me.refracdevelopment.simplegems.SimpleGems
author: RefracDevelopment
api-version: "1.13"
softdepend:
  - NBTAPI
  - PlaceholderAPI
  - Skulls
  - HeadDatabase
description: A simple gems economy plugin
website: https://discord.gg/EFeSKPg739
folia-supported: true