name: 'SimpleGems'
version: '${project.version}'
main: me.refracdevelopment.simplegems.plugin.SimpleGems
softdepend:
  - 'PlaceholderAPI'
  - 'Skulls'
  - 'HeadDatabase'
api-version: 1.13
authors:
  - 'RefracDevelopment'
  - 'Refrac'
description: 'A new gems economy plugin'
website: 'https://discord.refracdev.ml'