name: SimpleGems
version: '2.3-rc.3-SNAPSHOT'
main: me.refracdevelopment.simplegems.SimpleGems
author: RefracDevelopment
api-version: "1.13"
depend:
  - PlaceholderAPI
softdepend:
  - Skulls
  - HeadDatabase
description: A simple gems economy plugin
website: https://discord.refracdev.ml/

permissions:
  simplegems.*:
    default: op
    description: Gives all permissions
    children:
      simplegems.command.shop: true
      simplegems.command.top: true
      simplegems.command.balance: true
      simplegems.command.withdraw: true
      simplegems.command.pay: true
      simplegems.command.give: true
      simplegems.command.take: true
      simplegems.command.set: true
      simplegems.command.reload: true
      simplegems.command.update: true
      simplegems.command.version: true
  simplegems.command.shop:
    default: op
    description: Opens the gems shop
  simplegems.command.top:
    default: op
    description: Allows you to view top players balances
  simplegems.command.balance:
    default: op
    description: Shows player balances
  simplegems.command.withdraw:
    default: op
    description: Allows you to withdraw gems from your balance
  simplegems.command.pay:
    default: op
    description: Allows you to pay players gems from your balance
  simplegems.command.give:
    default: op
    description: Allows you to add players gems to their balance
  simplegems.command.take:
    default: op
    description: Allows you remove players gems from their balance
  simplegems.command.set:
    default: op
    description: Allows you to set a players gems balance
  simplegems.command.reload:
    default: op
    description: Allows you to reload the plugin and config files
  simplegems.command.update:
    default: op
    description: Allows you to manually update /gems top
  simplegems.command.version:
    default: op
    description: Allows you to check your installed version of SimpleGems