name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn clean install -B
          echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleGems-${{ env.PROJECT_VERSION }}
          path: '**/target/SimpleGems-${{ env.PROJECT_VERSION }}.jar'

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_number }} 
          name: SimpleGems v${{ github.run_number }}
          body: Auto-generated release for run #v${{ github.run_number }}
          artifacts: '**/target/SimpleGems-${{ env.PROJECT_VERSION }}.jar'
          draft: false
          prerelease: false
